dist: trusty
sudo: false
language: csharp
dotnet: 2.0.0
mono: none
script:
  - dotnet --version
  - dotnet restore ./GrEmit.sln --verbosity m
  - dotnet build --configuration Release ./GrEmit.sln
  - dotnet test --no-build --configuration Release ./GrEmit.Tests/GrEmit.Tests.csproj


