image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./GrEmit.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GrEmit.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --framework net45 ./GrEmit.Tests/GrEmit.Tests.csproj --logger "trx;LogFileName=gremit-tests-net45.trx"
  - cmd: dotnet test --no-build --configuration Release --framework netcoreapp2.0 ./GrEmit.Tests/GrEmit.Tests.csproj --logger "trx;LogFileName=gremit-tests-netcoreapp2.0.trx"

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:appveyor_job_id)", './GrEmit.Tests/TestResults/gremit-tests-net45.trx')
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:appveyor_job_id)", './GrEmit.Tests/TestResults/gremit-tests-netcoreapp2.0.trx')
