image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./GrEmit.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GrEmit.sln

test_script:
  - cmd: dotnet test --configuration Release ./GrEmit.Tests/GrEmit.Tests.csproj