image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./GrEmit.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GrEmit.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --framework net45 ./GrEmit.Tests/GrEmit.Tests.csproj --logger "trx;LogFileName=gremit-tests-net45.trx"
  - cmd: dotnet test --no-build --configuration Release --framework netcoreapp2.0 ./GrEmit.Tests/GrEmit.Tests.csproj --logger "trx;LogFileName=gremit-tests-netcoreapp2.0.trx"

after_test:
  - ps: |
      $jobId = $env:APPVEYOR_JOB_ID
      Write-Host $jobId
      $url = "https://ci.appveyor.com/api/testresults/mstest/$jobId";
      Write-Host $url
      $wc = New-Object 'System.Net.WebClient'
      $resultsNet45 = (Resolve-Path './GrEmit.Tests/TestResults/gremit-tests-net45.trx')
      Write-Host $resultsNet45
      $wc.UploadFile($url, $resultsNet45)
      $wc.UploadFile($url, (Resolve-Path './GrEmit.Tests/TestResults/gremit-tests-netcoreapp2.0.trx'))
